import { FormEvent, useState } from "react";
import { SEO } from "@/components/SEO";
import { supabase, backendConfigured } from "@/lib/supabase";

export default function Submit() {
  const [status,setStatus]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Submitting…");const f=new FormData(e.currentTarget);if(!supabase){setStatus("Submission backend is being connected. Please try again after the database is enabled.");return;}const {error}=await supabase.from("tool_submissions").insert({name:String(f.get("name")),website:String(f.get("website")),category:String(f.get("category")),description:String(f.get("description")),submitter_email:String(f.get("email")||"")||null});setStatus(error?"Could not submit right now. Please try again.":"Submitted successfully. Our team will review the listing before publishing.");if(!error)e.currentTarget.reset();}
  return <div className="mx-auto max-w-3xl px-4 py-10"><SEO title="Submit an AI Tool | Anjal AI" description="Submit an AI product to the Anjal AI directory for review." canonical={`${window.location.origin}/submit`} /><div className="rounded-3xl border border-line bg-white p-7 shadow-card dark:border-line-dark dark:bg-surface-dark"><h1 className="text-3xl font-semibold">Submit an AI tool</h1><p className="mt-2 text-slate">Listings are reviewed before they become public. We do not publish fabricated pricing or ratings.</p><form onSubmit={submit} className="mt-8 space-y-4"><input required name="name" placeholder="Tool name" className="w-full rounded-xl border border-line bg-transparent p-3 outline-none dark:border-line-dark"/><input required type="url" name="website" placeholder="Official website URL" className="w-full rounded-xl border border-line bg-transparent p-3 outline-none dark:border-line-dark"/><input required name="category" placeholder="Primary category" className="w-full rounded-xl border border-line bg-transparent p-3 outline-none dark:border-line-dark"/><textarea required name="description" placeholder="Short description" rows={4} className="w-full rounded-xl border border-line bg-transparent p-3 outline-none dark:border-line-dark"/><input type="email" name="email" placeholder="Your email (optional)" className="w-full rounded-xl border border-line bg-transparent p-3 outline-none dark:border-line-dark"/><button disabled={!backendConfigured} className="w-full rounded-xl bg-teal px-5 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Submit for review</button></form>{status&&<p className="mt-4 text-sm text-slate">{status}</p>}</div></div>;
}
